# Generated by Django 5.2.4 on 2025-07-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('customUrl', models.TextField()),
                ('datePublished', models.DateTimeField()),
                ('thumbnail', models.TextField()),
                ('statistics', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('channelTitle', models.TextField()),
                ('publishedAt', models.DateTimeField()),
                ('thumbnail', models.TextField()),
                ('views', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('favorites', models.IntegerField()),
                ('comments', models.IntegerField()),
                ('engagementRate', models.FloatField()),
            ],
        ),
    ]
